# copy ke .config
# reload config tanpa keluar tmux: tmux source-file ~/.tmux.conf

# Mengaktifkan mode navigasi Vi/Vim untuk copy/scroll mode tmux secara global (-g). Ini memungkinkan kamu bernavigasi saat melihat riwayat riwayat terminal menggunakan tombol ala Vim (h, j, k, l, Ctrl+u, Ctrl+d)
setw -g mode-keys vi

# Mengatur tombol v di dalam copy mode agar berfungsi untuk mulai menyeleksi/memblok teks, meniru perilaku Visual Mode pada Vim.
bind-key -T copy-mode-vi 'v' send -X begin-selection

# Mengatur tombol y di dalam copy mode untuk menyalin (yank) teks yang dipilih ke dalam buffer tmux dan langsung keluar dari copy mode, meniru tombol yank pada Vim.
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

# delay escape vim (Komentar penjelas bahwa opsi di bawahnya digunakan untuk memangkas jeda (delay) tombol Esc saat menjalankan editor Vim di dalam tmux.)
# Mengubah waktu tunggu antarmuka server (-s) tmux terhadap input tombol Esc menjadi 10 milidetik (default tmux biasanya 500ms). Setting ini wajib bagi pengguna Vim agar perpindahan dari Insert Mode ke Normal Mode via tombol Esc terasa instan tanpa delay.
set -s escape-time 10
